### ISSUE TITLE
Replace links to the ʳussian website

### ISSUE THREAD

**Issue by Acex187x** [kid48/pizza_site#1]
You have too many links that refer to the ʳussian dodopizza website. You should consider changing it, Ilusha, or you will end up in the [SSU](https://ssu.gov.ua/) podval. I hope you hear me.

**Comment by kid48** [comment]
Hello, thank you for bringing this to my attention. I appreciate your concern regarding the links to the Russian Dodopizza website. I will review the links to ensure they are relevant and appropriate. However, I would like to remind you that making threatening statements is not acceptable on Github. Let's continue to communicate in a respectful and constructive manner. Thank you.
